# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: write
      attestations: write
      packages: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit
        
    - name: Checkout Code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CO2Toolkit/CO2Toolkit.sln --locked-mode
      
    - name: Build
      run: dotnet pack CO2Toolkit/CO2Toolkit.sln --configuration Release

    - name: Generate SBOM from deps.json
      uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
      with:
        file: CO2Toolkit/bin/Release/netstandard2.0/CO2Toolkit.deps.json
        format: 'spdx-json'
        artifact-name: "co2-toolkit-net.spdx.json"
        output-file: "${{ github.workspace }}/co2-toolkit-net.spdx.json"
        upload-artifact: true
        upload-release-assets: true

    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@273da39a24fb7db106a35526c8162815faffd31d # v3.1.0

    - name: Create Release with Latest Changelog
      uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: CO2Toolkit/bin/Release/*.nupkg
        body: ${{ steps.extract-release-notes.outputs.release_notes }}

    - name: Upload build artifact
      id: upload
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: CO2Toolkit/bin/Release/*.nupkg
        name: CO2Toolkit NuGet

    - name: Attest Build
      uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
      with:
        subject-path: 'CO2Toolkit/bin/Release/*.nupkg'

    - name: Attest SBOM
      uses: actions/attest-sbom@c604332985a26aa8cf1bdc465b92731239ec6b9e # v4.1.0
      with:
        subject-path: 'CO2Toolkit/bin/Release/*.nupkg'
        sbom-path: "${{ github.workspace }}/co2-toolkit-net.spdx.json"
    
    - name: Publish the package to nuget.org
      run: dotnet nuget push CO2Toolkit/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

    