# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: write
      attestations: write
      packages: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
      with:
        egress-policy: audit
        
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CO2Toolkit/CO2Toolkit.sln --locked-mode
      
    - name: Build
      run: dotnet pack CO2Toolkit/CO2Toolkit.sln --configuration Release

    - name: Generate SBOM from deps.json
      uses: anchore/sbom-action@deef08a0db64bfad603422135db61477b16cef56 # v0.22.1
      with:
        file: CO2Toolkit/bin/Release/netstandard2.0/CO2Toolkit.deps.json
        format: 'spdx-json'
        artifact-name: "co2-toolkit-net.spdx.json"
        output-file: "${{ github.workspace }}/co2-toolkit-net.spdx.json"
        upload-artifact: true
        upload-release-assets: true

    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@202313ec7461b6b9e401996714484690ab1ae105 # v3.0.0

    - name: Create Release with Latest Changelog
      uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: CO2Toolkit/bin/Release/*.nupkg
        body: ${{ steps.extract-release-notes.outputs.release_notes }}

    - name: Upload build artifact
      id: upload
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        path: CO2Toolkit/bin/Release/*.nupkg
        name: CO2Toolkit NuGet

    - name: Attest Build
      uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f # v3.2.0
      with:
        subject-path: 'CO2Toolkit/bin/Release/*.nupkg'

    - name: Attest SBOM
      uses: actions/attest-sbom@4651f806c01d8637787e274ac3bdf724ef169f34 # v3.0.0
      with:
        subject-path: 'CO2Toolkit/bin/Release/*.nupkg'
        sbom-path: "${{ github.workspace }}/co2-toolkit-net.spdx.json"
    
    - name: Publish the package to nuget.org
      run: dotnet nuget push CO2Toolkit/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

    